### PR TITLE
grouped posts

### LINKED ISSUE #70: grouping mailing list posts
1. Ideal is to group the mailing lists like we had before the migration from app search to elastic search
2. A initial fix would be to label posts as original posts versus replies

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
closes #70

### CODE REVIEW

**Comment by Emmanuel-Develops** [comment]
> original

I have an helper sorting function from the original implementation that did the date sorting, I'm reusing it.
But checking the grouping, it doesn't always surface the original. 
Looking into this!

**Comment by Emmanuel-Develops** [comment]
> > original
> 
> I have an helper sorting function from the original implementation that did the date sorting, I'm reusing it. But checking the grouping, it doesn't always surface the original. Looking into this!

@adamjonas they should be well sorted now. please check

**Comment by adamjonas** [comment]
Looks good. Let's resolve it he conflicts and get it merged. 

Nice work.

**Comment by Emmanuel-Develops** [comment]
> Looks good. Let's resolve it he conflicts and get it merged.
> 
> Nice work.

Resolved!
Can we also remove the netlify integration/deployment since we've made the switch to vercel

**Pull request merged**
