### PR TITLE
Style/home page

### PR DESCRIPTION
**Pull request by IgboPharaoh**
Update landing page design

### CODE REVIEW

**Comment by Extheoisah** [comment]
The footer is not present in the homepage as it is in the design. We already have the footer component.

**Comment by Extheoisah** [comment]
The searchbar hero section doesn't entirely cover the full height of the screen
image

The scale of the CTA button looks off for me. I feel the text is too bold. Probably because we haven't added the design font from figma
image

**Comment by IgboPharaoh** [comment]
> The footer is not present in the homepage as it is in the design. We already have the footer component.

Ohhkk, I'll add it right away

**Comment by IgboPharaoh** [comment]
> The searchbar hero section doesn't entirely cover the full height of the screen. The 1st section should have the screen min-height image
> 
> The scale of the CTA button looks off for me. I feel the text is too bold. Probably because we haven't added the design font from figma image

The button does look big but that's the design specification from figma, another reason is he used 1920px screen width to design and that greatly affected the scale of elements and how they turned out

**Comment by Extheoisah** [comment]
> > The searchbar hero section doesn't entirely cover the full height of the screen. The 1st section should have the screen min-height image
> > The scale of the CTA button looks off for me. I feel the text is too bold. Probably because we haven't added the design font from figma image
> 
> The button does look big but that's the design specification from figma, another reason is he used 1920px screen width to design and that greatly affected the scale of elements and how they turned out

I'll send the deployment link to papersych so he examines and compare with the design.

**Review by Extheoisah — APPROVED** [review]

**Comment by kouloumos** [comment]
After merge: Some observations on the UI, @Extheoisah let me know if I should create issues for those:

- Activating the search bar reveals filters that appear beyond the visible window, requiring scrolling for access.
- The arrow for advancing to the next section remains visible even after displaying the filters.

Screencastfrom2024-03-2912-22-19-ezgif com-video-to-gif-converter

-Initiating a search without input leads to an irregular state where the footer overlays the top, hiding other homepage elements. In this case the URL is  `<domain>?search=`, therefore even refreshing does not reset the page.

Screencastfrom2024-03-2912-29-11-ezgif com-video-to-gif-converter

**Comment by IgboPharaoh** [comment]
I'm looking it right away

**Comment by kouloumos** [comment]
@IgboPharaoh the second issue that I [mentioned here](https://github.com/bitcoinsearch/bitcoinsearch-app/pull/93#issuecomment-2027047904) hasn't been solved.

**Comment by kouloumos** [comment]
> I just checked the latest [deployment](https://bitcoinsearch-l4wko3rxe-btc-knowledge-base.vercel.app/) from emmanuel's last pr on staging and the issue was non-existent. Just to be clear, the second issue we are talking about is `The arrow for advancing to the next section remains visible even after displaying the filters.` right ?

Sorry, my mistake, I meant the third issue, apologies for no being clear
> Initiating a search without input leads to an irregular state where the footer overlays the top, hiding other homepage elements. In this case the URL is <domain>?search=, therefore even refreshing does not reset the page.

I posted 2 videos, so I kind of referring to the second video as second issue.

**Comment by IgboPharaoh** [comment]
No worries. I set conditions where the footer is only displayed if there is
a homepage or a search query or search results returns a value. But I'll
still test it out in the latest deployment to fix this.

**Comment by IgboPharaoh** [comment]
I couldn't replicate the 3rd issue, you can try this deployment link: [latest-deployment](https://bitcoinsearch-l4wko3rxe-btc-knowledge-base.vercel.app/). This is the format of the link I tried:  `https://bitcoinsearch-l4wko3rxe-btc-knowledge-base.vercel.app/?search=` and the footer was not present.

Perhaps you can provide more context on this if I am not following through correctly

**Comment by kouloumos** [comment]
> I couldn't replicate the 3rd issue. you can try this deployment link: [latest-deployment](https://bitcoinsearch-l4wko3rxe-btc-knowledge-base.vercel.app/). This is the format of the link I tried: `https://bitcoinsearch-l4wko3rxe-btc-knowledge-base.vercel.app/?search=` and the footer was not present.
> 
> Perhaps you can provide more context on this if I am not following through correctly

You are right that right now the footer issue is solved. But, what's the point of allowing that empty search query? Empty search query takes the page into a kind of intermediary state, which seems not useful. Why not disable the button when search is empty in order to avoid that?

**Comment by IgboPharaoh** [comment]
I'm happy to know the issue has been fixed.

**Comment by kouloumos** [comment]
> I don't think it takes it into an intermediary state, it just returns an empty result. We can investigate the query code to see if it returns if the router query is empty

Try searching [google](https://www.google.com/), [bing](https://www.bing.com/) or [duckduckgo](https://duckduckgo.com/) with an  empty query string.

**Pull request merged**
